FROM node:20-alpine
RUN corepack enable
WORKDIR /workspace
COPY package.json pnpm-workspace.yaml tsconfig.base.json ./
COPY apps ./apps
COPY packages ./packages
RUN pnpm install
CMD ["sh", "-c", "pnpm install && pnpm dev"]
