import { AgentNote, Fragment, Project } from '@/lib/vault/types';

export const projects: Project[] = [
  {
    id: 'murmur-creator-studio',
    title: 'MurMur Creator Studio',
    description: 'A mobile workspace to shape ideas into execution-ready creative systems.',
    type: 'Creative OS',
    status: 'Active',
    tags: ['workflow', 'creative', 'product'],
    maturityScore: 81,
    updatedAt: '2026-03-11',
    vision: 'Turn scattered creative sparks into a repeatable founder operating system.',
    problem: 'Ideas live in disconnected tools and get lost before becoming projects.',
    user: 'Solo creator juggling prompts, drafts, prototypes, and strategy notes.',
    features: ['Idea inbox', 'Project structuring board', 'Agent reflection summaries'],
    nextSteps: ['Validate dashboard flow', 'Test export readability', 'Add tagging heuristics'],
  },
  {
    id: 'murmur-music-dna-engine',
    title: 'MurMur Music DNA Engine',
    description: 'A system for extracting motifs, creative rules, and signature patterns from music sketches.',
    type: 'Music Intelligence',
    status: 'Incubating',
    tags: ['audio', 'ai', 'analysis'],
    maturityScore: 63,
    updatedAt: '2026-03-09',
    vision: 'Map artistic identity into reusable composition blueprints.',
    problem: 'Music experiments remain fragments with no continuity or archive context.',
    user: 'Independent artist and producer developing modular sonic systems.',
    features: ['DNA motif capture', 'Session lineage mapping', 'Prompt-to-track concept cards'],
    nextSteps: ['Define tagging taxonomy', 'Design fragment-linking UX', 'Simulate track export brief'],
  },
  {
    id: 'murmur-archive-vault',
    title: 'MurMur Archive Vault',
    description: 'The premium archive app for converting chaos into structured, buildable projects.',
    type: 'Archive Platform',
    status: 'Active',
    tags: ['archive', 'dashboard', 'pwa'],
    maturityScore: 74,
    updatedAt: '2026-03-12',
    vision: 'Make archived fragments instantly shapeable into actionable products.',
    problem: 'High-volume idea archives lack structure and extraction workflows.',
    user: 'A high-output founder with notes across tools, systems, and unfinished concepts.',
    features: ['Project vault', 'Agent guidance stream', 'Brief export studio'],
    nextSteps: ['Polish touch interactions', 'Connect capture form to API route', 'Add lightweight offline cache'],
  },
  {
    id: 'horten-pilot',
    title: 'Horten Pilot',
    description: 'Local pilot intelligence stack for place-based experiments and civic design.',
    type: 'Pilot Program',
    status: 'Draft',
    tags: ['local', 'pilot', 'intelligence'],
    maturityScore: 45,
    updatedAt: '2026-03-05',
    vision: 'Create a grounded intelligence loop between local signals and strategic action.',
    problem: 'Pilot insights are captured but never organized into reusable structures.',
    user: 'Founder coordinating multi-stakeholder test projects in one locality.',
    features: ['Signal board', 'Pilot brief templates', 'Outcome memory bank'],
    nextSteps: ['Clarify pilot metrics', 'Prototype stakeholder dashboard', 'Draft launch narrative'],
  },
  {
    id: 'murmur-constellation',
    title: 'MurMur Constellation',
    description: 'Meta-layer that connects all MurMur projects into a strategic roadmap.',
    type: 'Meta Strategy',
    status: 'On Hold',
    tags: ['portfolio', 'meta', 'strategy'],
    maturityScore: 58,
    updatedAt: '2026-02-28',
    vision: 'Reveal relationships between projects so compounding value is visible.',
    problem: 'Portfolio-level strategy gets buried beneath daily ideation.',
    user: 'Solo builder managing many active and dormant initiatives at once.',
    features: ['Cross-project map', 'Dependency trace', 'Strategic timing dashboard'],
    nextSteps: ['Reframe north-star metric', 'Define cross-project tags', 'Review activation sequence'],
  },
];

export const fragments: Fragment[] = [
  {
    id: 'f1',
    title: 'black/gold premium dashboard',
    content: 'Use cinematic contrast, soft gold borders, and concise cards with large touch zones.',
    type: 'Note',
    tags: ['ui', 'design'],
    linkedProjectIds: ['murmur-archive-vault'],
    createdAt: '2026-03-12',
  },
  {
    id: 'f2',
    title: 'export to GitHub README',
    content: 'Generate a clean markdown summary with sections for vision, users, features, and next steps.',
    type: 'System Idea',
    tags: ['export', 'markdown'],
    linkedProjectIds: ['murmur-creator-studio', 'murmur-archive-vault'],
    createdAt: '2026-03-11',
  },
  {
    id: 'f3',
    title: 'modular multi-agent archive',
    content: 'Pair strategist + builder notes to reduce drift between concept and execution.',
    type: 'Prompt',
    tags: ['agents', 'archive'],
    linkedProjectIds: ['murmur-archive-vault', 'murmur-constellation'],
    createdAt: '2026-03-10',
  },
  {
    id: 'f4',
    title: 'artist workflow vault',
    content: 'Capture song ideas, texture notes, and production prompts into reusable scenes.',
    type: 'Flow',
    tags: ['music', 'workflow'],
    linkedProjectIds: ['murmur-music-dna-engine'],
    createdAt: '2026-03-09',
  },
  {
    id: 'f5',
    title: 'startup brief generator',
    content: 'Export investor-ready one-pager from project structure and agent notes.',
    type: 'System Idea',
    tags: ['startup', 'brief'],
    linkedProjectIds: ['murmur-archive-vault', 'horten-pilot'],
    createdAt: '2026-03-08',
  },
  {
    id: 'f6',
    title: 'local pilot intelligence system',
    content: 'Turn qualitative field notes into actionable milestones for a 30-day pilot.',
    type: 'Note',
    tags: ['pilot', 'local'],
    linkedProjectIds: ['horten-pilot'],
    createdAt: '2026-03-07',
  },
];

export const agentNotes: AgentNote[] = [
  {
    id: 'a1',
    projectId: 'murmur-archive-vault',
    agentType: 'Strategist',
    title: 'Clarify transformation metric',
    content: 'Track how many fragments become structured project sections each week.',
    priority: 'High',
  },
  {
    id: 'a2',
    projectId: 'murmur-archive-vault',
    agentType: 'Architect',
    title: 'Prepare API seam',
    content: 'Define a single service layer for data calls so Netlify functions can attach later.',
    priority: 'Medium',
  },
  {
    id: 'a3',
    projectId: 'murmur-archive-vault',
    agentType: 'Builder',
    title: 'Prioritize capture speed',
    content: 'Keep capture interaction under three taps to reduce drop-off during idea flow.',
    priority: 'High',
  },
  {
    id: 'a4',
    projectId: 'murmur-archive-vault',
    agentType: 'Curator',
    title: 'Tighten fragment taxonomy',
    content: 'Use limited fragment types to improve retrieval and reduce archive entropy.',
    priority: 'Medium',
  },
  {
    id: 'a5',
    projectId: 'murmur-archive-vault',
    agentType: 'Reflector',
    title: 'Preserve intent snapshots',
    content: 'Store a short “why now” note per project update to preserve creative direction.',
    priority: 'Low',
  },
];
