CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE IF NOT EXISTS posting_time_arms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  account_id UUID NOT NULL,
  hour_slot INT NOT NULL CHECK (hour_slot BETWEEN 0 AND 23),
  alpha DOUBLE PRECISION NOT NULL DEFAULT 1,
  beta DOUBLE PRECISION NOT NULL DEFAULT 1,
  total_trials INT NOT NULL DEFAULT 0,
  total_reward DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (account_id, hour_slot)
);

ALTER TABLE posts
  ADD COLUMN IF NOT EXISTS reward DOUBLE PRECISION;
